services:
  lurk:
    image: ${LURK_IMAGE:-ghcr.io/jackra1n/lurk:latest}
    container_name: lurk
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    ports:
      - "1738:3000"
    restart: unless-stopped
